// GENERATED by scripts/build-wallpapers.mjs — do not edit by hand.
// Regenerate with: node scripts/build-wallpapers.mjs [sourceDir]

export interface WallpaperAsset {
  /** Original filename, preserved exactly as exported. Contains a space. */
  readonly filename: string;
  /** Byte size of the untouched original, shown on the download control. */
  readonly bytes: number;
  /** 16px WebP data URI painted underneath the preview until it decodes. */
  readonly blur: string;
}

export const NATIVE_WIDTH = 1572;
export const NATIVE_HEIGHT = 3408;

export const assets: Readonly<Record<string, WallpaperAsset>> = {
  '01': {
    filename: "wall 1.jpg",
    bytes: 7453736,
    blur:
      'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBQCdASoQACMAPtlWpUyoJKOiNVgIAQAbCWYAnTLevOgb7IThY7Fv6rqNPFB7nHtAAP7yo9+2dLmj33Ht8Jkj9XZO8QUZeHKcI0+m0sDFSh58HRuP6EYoyPpPJiQ6b2aiNuCaHU5AGwa15C9fy74skbC42Sg1wzldccyjizraIysNOkhAAA==',
  },
  '02': {
    filename: "wall 2.jpg",
    bytes: 6772163,
    blur:
      'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABwBACdASoQACMAPs1SoUynpKMiNUgA8BmJZAAAehvVleLZ1SZiq3I+MfijGAD+8qQdIce49miq+X1El+4uHKZz+UN6v/8ZFvucHT77RpkwBx7kktJ+O83FAVakVSpUkiEMPtgV08xC/gLrowP6SfrhjpxY16+0Q7YvfRukmT/I8c4A',
  },
  '03': {
    filename: "wall 3.jpg",
    bytes: 5393299,
    blur:
      'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQBACdASoQACMAPs1SoUynpKMiNUgA8BmJYwDG9C0YmrEOGEU6T9VhhSpR4pKqAAD+y1gH+OUROs8HZ3pdycdR6nkLz6WP9VU9frWyr1eYU5zej/wiBq+gbPKPLhXJlhVavk0rB4seTFcJQYzb+zzoIsVLk+wx6kEAAA==',
  },
  '04': {
    filename: "wall 4.jpg",
    bytes: 7635615,
    blur:
      'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoQACMAPs1Wo0ynpSMiNUgA8BmJaACsOUFS3gaBb6BrefYdYkUPP2pNvL8XIAD+9CUjxAfIER2x8vMMSQddvjZDxim9NLk1VJe8oUNMTrSAav+ZCimLt7+tOskqzDCF9okABjILcHYLrK9/SpxrMNfRmQtDjPx7ZTkiJ8xxt2OjnSxJvAA=',
  },
  '05': {
    filename: "wall 5.jpg",
    bytes: 7293374,
    blur:
      'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwBACdASoQACMAPs1WokynpKMiNUgA8BmJZAB4MgXJE7l4PrENBS1t8EZNBKrju4AA/u6Dt26nbO8KO9YprOkIRDjbJVf4lwf/ZX0vOCez7AlYH+dO7POgTZKPpSBJ78asGZV6ZbhqkU4yFuLiDGHlJxDe1wysvkdA1inszZ0PFVDZJqa5Dp+8ofQAAA==',
  },
  '06': {
    filename: "wall 6.jpg",
    bytes: 5273491,
    blur:
      'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQBACdASoQACMAPs1WokynpSMiNUgA8BmJYwDKAC0q1ogPxiw7pqYLmdhxY866gAD+7oO9uCPr5RPvsbLB7kTnO81v2UwSyPyOwhuwy95XQGnl1CEDgzZH7G0ny8eNnr21tTVHGFgu7z0R6rIaJmFY4kV525Zo3zkFgAAA',
  },
  '07': {
    filename: "wall 7.jpg",
    bytes: 7336144,
    blur:
      'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoQACMAPs1SoUynpKMiNUgA8BmJZACdMvZ7KDhDeA+Fz4Wtr2dCPezcn7k0YAD+7oei/C0oyKhDVGkiX8Dm450lc9aL8TqyEaq0npvbZvSkqELWCzGUw2p0uYpaQzMSlLWBllxyK2hHybC3P7ernAZfAMzczHG3VG5f/1WpZ5AGjVjBQAA=',
  },
  '08': {
    filename: "wall 8.jpg",
    bytes: 5379134,
    blur:
      'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoQACMAPt1UpUyopCOiNVgIARAbiWcAsOxFbKTNiRf8c33sS3Y+8DlXlQAA/vnCO24hCmdGwkJt1LBc4ikUPJ8uoHlpNMlKFBc0VxoWuI6Mp1dEtvfua5KbWLgyM4PQPtrHjkquBNSwmpgP8YDEgAAA',
  },
  '09': {
    filename: "wall 9.jpg",
    bytes: 7415542,
    blur:
      'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwBACdASoQACMAPs1Wo0ynpSMiNUgA8BmJZgC7LwJ6AAgHphWMFvZt9EtlyuLo5AAA/vKkHSHGRHHBAEHdIlOxAcenWj2PAfxMZJLD7K+TiF/RrgI4oOx3oyXu0f5UCubtD6ZyxEc5qOTlSd4XspbDSqXavdUdFPYKNzaqFlHeijXeTmUDAAAA',
  },
  '10': {
    filename: "wall 10.jpg",
    bytes: 6677508,
    blur:
      'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoQACMAPs1UoUynpKMiNUgA8BmJZAAAevv024aUwMXaRr2eDLJXQAD+9CTJtDQxBtgDlF/VWOiWrKo5PyYtv9TpQfBf19lj2Jeq5XzyFRs70FpHbSQHJXNUW1p7sq25JpFZgvNc752t7bniVIShMQ4V2oIOidWqO1p8geWl6fIF9AAA',
  },
  '11': {
    filename: "wall 11.jpg",
    bytes: 4570215,
    blur:
      'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQBACdASoQACMAPtVco0yoJaMiNVgIAQAaiWUAAL8N/BpdF7YJRgdup/EXovSsAAD++E5yfHsP6IMQL+ScMJKH1k8D2mWU5HiGOJterCUxGBs/GeLLi7uzzIacxlEwcj3Q//19yqRjkB/nMZ4AAA==',
  },
  '12': {
    filename: "wall 12.jpg",
    bytes: 5598750,
    blur:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoQACMAPs1WokynpSMiNUgA8BmJYwDImC0owqi73opCAGAI52/lAAD+8MsNS2krAetG7CpBo8BzTnEQGm5OuhH5HWCkp68Zu1Lx438Gz+UjRPRpKeYZcUrmHW6EZf4pcGkv2UtkU4eDkTuqal6XR8/jd9uIWhQQAAA=',
  },
  '13': {
    filename: "wall 13.jpg",
    bytes: 5361095,
    blur:
      'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBQCdASoQACMAPtVco0yoJaMiNVgIAQAaiWUAt7hFlMTv3o2WbSMIO+nBN2mOsBAAAP7svL9OzHevooTVs70t9WxEqrkwD8nVm7VNafg2SKbiRbX4zzzJosV9hpEHQP5TZ2RMoVpXD8OOEdqO+xSzFGFNmWRKhW7XGez+/tgIAA==',
  },
  '14': {
    filename: "wall 14.jpg",
    bytes: 6498456,
    blur:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoQACMAPt1cqU0opSQiKqwBEBuJYgCdABZsqkdqJ1cFXNUyOdzYALd2IAD+9CTxEukPzUOthB9pkaFfnZwv0QdFGckW8ToPeuJXANaVThmypKD/+1GQ35HzIMBtXRvT4pWx1GgS/MFNYgFNfoIhrYIvlqdt+SgAAAA=',
  },
  '15': {
    filename: "wall 15.jpg",
    bytes: 3328339,
    blur:
      'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoQACMAPtFYo0yoJSMiNUgBABoJaQAAehvriheysh2yjBe2AKFwIgAA/vaJpFf6/mf5bSmYrTfH2I9737g8tBdHDeJ/O7kQMDmryNOGouNIXITrMPB252AAAAA=',
  },
  '16': {
    filename: "wall 16.jpg",
    bytes: 7450106,
    blur:
      'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBQCdASoQACMAPt1gpU4opaMiKqwBEBuJZgCdMoACL4Py8ZhhZ+TdGRor5jnOJorlAAD+8qPftnS5o9yljcrPX/hzyd9QYJcO2yDKb6bSx2oF7EVbBRk5KGgaE/nKem9VOXl+HttwLLj00Cx/9vnoYzRm09uFwSiKpC0E07h5CF8B8AebEAAA',
  },
  '17': {
    filename: "wall 17.jpg",
    bytes: 6999499,
    blur:
      'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBQCdASoQACMAPtlcpEyoJSOiNVgIAQAbCWIAnTMYAjeFmzUz2dXk06WgcW3dYM5yAAD+9CUjxAfIER2x8vN4MSinNDbJR8jk0uAPqksrklYnwozRMjb/SStvhed3nU6G/2sDob5M8eikVtd5izF9yX1oAhmhEpVPCzofwcJKzP78T0impoAA',
  },
  '18': {
    filename: "wall 18.jpg",
    bytes: 5703354,
    blur:
      'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwBACdASoQACMAPs1WokynpSMiNUgA8BmJZQDG9CwOngdk3f6W8Sxy0mJlJ6YEOgAA/vVv2kVypEaBlJE+hyh9Djq3WkAQlnCc7HuC/zqq2C6MejDvGmCm7pQXS3+7QMMGIjoCTl8m/IU3bwewOCBVU+l2Ae9xgK2TgAAA',
  },
  '19': {
    filename: "wall 19.jpg",
    bytes: 6170585,
    blur:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoQACMAPs1SoUynpKMiNUgA8BmJQBadBYHTwmitSx/SxAsftjXUAAD+4vX7m9rhL6JbauoKa6BtiKlDg+aj/iV19fe+r3XLjDf805cTS67BL2AzuF+laZVb4kB5VohbjHX9oYOU6JIQ9KqWUTx1VtHdnmStSlMSAAA=',
  },
  '20': {
    filename: "wall 20.jpg",
    bytes: 5824192,
    blur:
      'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBACdASoQACMAPs1SoUynpKMiNUgA8BmJYgAAehwJiGdfQViRpL7BtSygAP72iLRIcXN8Shsfi5R/96XbQLu7eaa4Zi/J8Ax7ilsNLyKs4USxGwHqS3gcnzpk/JRKIEpY7OGIy+IWgg9U0IEAAA==',
  },
  '21': {
    filename: "wall 21.jpg",
    bytes: 6143531,
    blur:
      'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBACdASoQACMAPs1SoUynpKMiNUgA8BmJQBadBaW/NLpaQTsCYudtRlaSSFAQAAD+8MsNSwjcVfJ8QZNphkxNcYdRWw9v7U/KzzWUR1UdtKnNxz2D+dM9rOXY7nC6W6WDR58n6IFIJnEfu9hJCHpU7cDqk/JxZJX1Tq3MsKAAAA==',
  },
};
